### ISSUE TITLE
Rewrite from `python-bridge` to `tensorflow.js`, so that we can run facenet in Browser natively!

### ISSUE THREAD

**Issue by zixia** [zixia/node-facenet#155]
### Todo

- [ ] implenment facenet & mtcnn alghorithm to JS
- [ ] train in JS
- [ ] build in purely js
- [ ] modulize an angular module

### See Also

- Tensor Flow JS - https://js.tensorflow.org/

**Comment by sziraqui** [comment]
Hi, has there been any progress on this? Are there any major hardles in implementing facenet with tfjs as of today?

**Comment by huan** [comment]
@sziraqui Thank you for your attention.

You can have a look at face.js at https://github.com/justadudewhohacks/face-api.js, which is currently working very well with tfjs.
